[project]
name = 'files'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.compute-resource]
path = 'contracts/compute-resource.clar'
clarity_version = 3
epoch = 3.0

[contracts.dataset-quality]
path = 'contracts/dataset-quality.clar'
clarity_version = 3
epoch = 3.0

[contracts.token]
path = 'contracts/token.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
